### ISSUE TITLE
Plan for updating

### ISSUE THREAD

**Issue by GHNewbiee** [web-padawan/awesome-lit#55]
Do you have any plan for updating the resources to be complied with new **lit** library? *Tia*

**Comment by web-padawan** [comment]
Thanks for your issue. Yes I do have some good materials to be added and hopefully will update this list quite soon.

**Comment by web-padawan** [comment]
The list is now updated for Lit 2, check out the new Codelabs and Tutorials sections. 
A lot of old content is removed and some articles have been moved to Archive.
