### ISSUE TITLE
Research on the addition of the new items to the list

### ISSUE THREAD

**Issue by web-padawan** [web-padawan/awesome-lit#9]
> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend. 

There are some community projects which are in early stage at this point. Instead of adding them immediately, per above quote, we should confirm if they can be recommended.

This is a tracking issue to add all the stuff which is possibly worth mentioning in the list.
Any good log posts can be added directly but for projects we still need _some_ research.

Some rules:
1. each suggested item should be in a separate comment
2. once the item is added, comment can be removed

**Comment by web-padawan** [comment]
create-evergreen-app: https://github.com/ProjectEvergreen/create-evergreen-app

Current version: 0.2.0
There are some opened issues so at this point it might be a bit early to add this here.
Will reconsider once the author himself considers it stable.

**Comment by web-padawan** [comment]
lit-css: https://github.com/bashmish/lit-css

Current version: 0.1.2
My plan is to experiment with this project, also talked to author who mentioned that there might be also upcoming LitElement mixin implementation based on this solution. Will consider adding to the list after that, the "Inspired solutions" section looks like a right place for that.

**Comment by web-padawan** [comment]
haunted: https://github.com/matthewp/haunted

Current version: (no release yet)
React's Hook API but for standard web components and lit-html.
Consider adding it once it gets a release and some attraction.

**Comment by thescientist13** [comment]
> create-evergreen-app
Hey @web-padawan , that's me 👋 

Really appreciate all the work you've put into the community, and would definitely happy to be a part of this. 

I think I would categorize our open issues as more along the lines of feature requests we are looking to explore for the project, as either code or supplemental documentation, which we have a lot of in our wiki (and are currently moving to a website as we speak)
https://github.com/ProjectEvergreen/create-evergreen-app/wiki/

So with that little intro, let me know if there are other issues i could help address.  @hutchgrant has been a big help and has been contributing actively and we're now on 0.4.2 release, and definitely have a lot more activities planned for this year which should be showing up in GitHub over the next few weeks.

Thanks, and let me know your thoughts.

**Comment by kwaclaw** [comment]
lit-mvvm: https://github.com/kwaclaw/KdSoft.lit-mvvm and https://www.npmjs.com/package/@kdsoft/lit-mvvm

Based on lit-element. An alternative that replaces observable properties with an observable and shareable view model. It also separates out render scheduling to be pluggable.

There is also a fork of the pwa starter kit at https://github.com/kwaclaw/pwa-starter-kit. The template-mvvm-lit-plain branch (based on template-no-redux) is using lit-mvvm.

**Comment by web-padawan** [comment]
https://github.com/rxdi/starter-client-side-lit-html

Last updated 21 days ago. Will check the status and see how the project evolves.

**Comment by web-padawan** [comment]
https://github.com/paulchiu/lit-html-typescript-parcel-starter

Last updated 17 days ago, will keep an eye on it.

**Comment by web-padawan** [comment]
https://github.com/extensible-cms/ecms-ui-atoms

Pre-alpha with "Chrome support only". Will possibly add once it is in a better shape 😄

**Comment by web-padawan** [comment]
https://github.com/DoubleTrade/lit-datepicker

Version 0.0.7 at the moment. Will add later after when the component gets mature.
